# coding: utf-8

"""
    IPNetworks

     An IP network allows you to define an IP subnet in your account. The size of the IP subnet and the set IP addresses in the subnet are determined by the IP address prefix that you specify while creating the IP network. These IP addresses aren't part of the common pool of Oracle-provided IP addresses used by the shared network. When you add an instance to an IP network, the instance is assigned an IP address in that subnet. You can assign IP addresses to instances either statically or dynamically, depending on your business needs. So you have complete control over the IP addresses assigned to your instances. For more information, see <a target=\"_blank\" href=\"http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=STCSG-GUID-B62FE52B-CD56-43D9-AB42-354D5C8C5AA1\">Managing IP Networks</a> in <em>Using Oracle Compute Cloud Service (IaaS)</em>

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.ip_networks_api import IPNetworksApi


class TestIPNetworksApi(unittest.TestCase):
    """ IPNetworksApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.ip_networks_api.IPNetworksApi()

    def tearDown(self):
        pass

    def test_add_ip_network(self):
        """
        Test case for add_ip_network

        Create an IP Network
        """
        pass

    def test_delete_ip_network(self):
        """
        Test case for delete_ip_network

        Delete an IP Network
        """
        pass

    def test_get_ip_network(self):
        """
        Test case for get_ip_network

        Retrieve Details of an IP Network
        """
        pass

    def test_list_ip_network(self):
        """
        Test case for list_ip_network

        Retrieve Details of all IP Networks in a Container
        """
        pass

    def test_update_ip_network(self):
        """
        Test case for update_ip_network

        Update an IP Network
        """
        pass


if __name__ == '__main__':
    unittest.main()
