# coding: utf-8

"""
    Instances

    An Oracle Compute Cloud Service instance is a virtual machine running a specific operating system and with CPU and memory resources that you specify. See <a target=\"_blank\" href=\"http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=STCSG-GUID-F928F362-2DB6-4E45-843F-C269E0740A36\">About Instances</a> in <em>Using Oracle Compute Cloud Service (IaaS)</em>.<p>You can view and delete instances using the HTTP requests listed below.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.instance_put_request import InstancePutRequest


class TestInstancePutRequest(unittest.TestCase):
    """ InstancePutRequest unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstancePutRequest(self):
        """
        Test InstancePutRequest
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.instance_put_request.InstancePutRequest()
        pass


if __name__ == '__main__':
    unittest.main()
