# coding: utf-8

"""
    Authenticate

    A POST request to this resource authenticates the specified user and returns an authentication cookie, which you can specify in subsequent API calls to Oracle Compute Cloud Service.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.authenticate_api import AuthenticateApi


class TestAuthenticateApi(unittest.TestCase):
    """ AuthenticateApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.authenticate_api.AuthenticateApi()

    def tearDown(self):
        pass

    def test_add_authenticate(self):
        """
        Test case for add_authenticate

        Authenticate User
        """
        pass


if __name__ == '__main__':
    unittest.main()
