# coding: utf-8

"""
    IPAssociations

    An IP association is a link between an IP reservation and the vcable of an instance. A vcable is an attachment point to a specific network interface of an instance. A vcable is created automatically when an instance is created and is deleted when the instance is deleted.<p>You can create, delete, and view IP associations using the HTTP requests listed below.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.ip_association_post_request import IPAssociationPostRequest


class TestIPAssociationPostRequest(unittest.TestCase):
    """ IPAssociationPostRequest unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIPAssociationPostRequest(self):
        """
        Test IPAssociationPostRequest
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.ip_association_post_request.IPAssociationPostRequest()
        pass


if __name__ == '__main__':
    unittest.main()
