# coding: utf-8

"""
    IPReservations

    An IP reservation is the allocation of a public IP address from an IP address pool. After creating an IP reservation, you can associate it with an instance by using an IP association, to enable access between the Internet and the instance.<p>You can add, delete, update, and view IP reservations using the HTTP requests listed below.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.ip_reservations_api import IPReservationsApi


class TestIPReservationsApi(unittest.TestCase):
    """ IPReservationsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.ip_reservations_api.IPReservationsApi()

    def tearDown(self):
        pass

    def test_add_ip_reservation(self):
        """
        Test case for add_ip_reservation

        Create an IP Reservation
        """
        pass

    def test_delete_ip_reservation(self):
        """
        Test case for delete_ip_reservation

        Delete an IP Reservation
        """
        pass

    def test_discover_ip_reservation(self):
        """
        Test case for discover_ip_reservation

        Retrieve Names of all IP Reservations and Subcontainers in a Container
        """
        pass

    def test_discover_root_ip_reservation(self):
        """
        Test case for discover_root_ip_reservation

        Retrieve Names of Containers
        """
        pass

    def test_get_ip_reservation(self):
        """
        Test case for get_ip_reservation

        Retrieve Details of an IP Reservation
        """
        pass

    def test_list_ip_reservation(self):
        """
        Test case for list_ip_reservation

        Retrieve Details of all IP Reservations in a Container
        """
        pass

    def test_update_ip_reservation(self):
        """
        Test case for update_ip_reservation

        Update an IP Reservation
        """
        pass


if __name__ == '__main__':
    unittest.main()
