# coding: utf-8

"""
    Authenticate

    A POST request to this resource authenticates the specified user and returns an authentication cookie, which you can specify in subsequent API calls to Oracle Compute Cloud Service.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.authenticate import Authenticate


class TestAuthenticate(unittest.TestCase):
    """ Authenticate unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthenticate(self):
        """
        Test Authenticate
        """
        model = swagger_client.models.authenticate.Authenticate()


if __name__ == '__main__':
    unittest.main()
