# coding: utf-8

"""
    IPNetworks

     An IP network allows you to define an IP subnet in your account. The size of the IP subnet and the set IP addresses in the subnet are determined by the IP address prefix that you specify while creating the IP network. These IP addresses aren't part of the common pool of Oracle-provided IP addresses used by the shared network. When you add an instance to an IP network, the instance is assigned an IP address in that subnet. You can assign IP addresses to instances either statically or dynamically, depending on your business needs. So you have complete control over the IP addresses assigned to your instances. For more information, see <a target=\"_blank\" href=\"http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=STCSG-GUID-B62FE52B-CD56-43D9-AB42-354D5C8C5AA1\">Managing IP Networks</a> in <em>Using Oracle Compute Cloud Service (IaaS)</em>

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.ip_association_discover_response import IPAssociationDiscoverResponse
from .models.ip_association_list_response import IPAssociationListResponse
from .models.ip_association_post_request import IPAssociationPostRequest
from .models.ip_association_response import IPAssociationResponse
from .models.instance_discover_response import InstanceDiscoverResponse
from .models.instance_list_response import InstanceListResponse
from .models.instance_put_request import InstancePutRequest
from .models.instance_response import InstanceResponse
from .models.ip_reservation_discover_response import IPReservationDiscoverResponse
from .models.ip_reservation_list_response import IPReservationListResponse
from .models.ip_reservation_post_request import IPReservationPostRequest
from .models.ip_reservation_put_request import IPReservationPutRequest
from .models.ip_reservation_response import IPReservationResponse
from .models.ip_network_list_response import IpNetworkListResponse
from .models.ip_network_post_request import IpNetworkPostRequest
from .models.ip_network_put_request import IpNetworkPutRequest
from .models.ip_network_response import IpNetworkResponse
from .models.authenticate import Authenticate
from .models.interval import Interval
from .models.daily_weekly_interval import DailyWeeklyInterval
from .models.hourly_interval import HourlyInterval

# import apis into sdk package
from .apis.ip_associations_api import IPAssociationsApi
from .apis.instances_api import InstancesApi
from .apis.ip_reservations_api import IPReservationsApi
from .apis.ip_networks_api import IPNetworksApi
from .apis.authenticate_api import AuthenticateApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration
