# coding: utf-8

"""
    Instances

    An Oracle Compute Cloud Service instance is a virtual machine running a specific operating system and with CPU and memory resources that you specify. See <a target=\"_blank\" href=\"http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=STCSG-GUID-F928F362-2DB6-4E45-843F-C269E0740A36\">About Instances</a> in <em>Using Oracle Compute Cloud Service (IaaS)</em>.<p>You can view and delete instances using the HTTP requests listed below.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .ip_association_discover_response import IPAssociationDiscoverResponse
from .ip_association_list_response import IPAssociationListResponse
from .ip_association_post_request import IPAssociationPostRequest
from .ip_association_response import IPAssociationResponse
from .instance_discover_response import InstanceDiscoverResponse
from .instance_list_response import InstanceListResponse
from .instance_put_request import InstancePutRequest
from .instance_response import InstanceResponse
from .ip_reservation_discover_response import IPReservationDiscoverResponse
from .ip_reservation_list_response import IPReservationListResponse
from .ip_reservation_post_request import IPReservationPostRequest
from .ip_reservation_put_request import IPReservationPutRequest
from .ip_reservation_response import IPReservationResponse
from .ip_network_list_response import IpNetworkListResponse
from .ip_network_post_request import IpNetworkPostRequest
from .ip_network_put_request import IpNetworkPutRequest
from .ip_network_response import IpNetworkResponse
from .authenticate import Authenticate
from .interval import Interval
from .daily_weekly_interval import DailyWeeklyInterval
from .hourly_interval import HourlyInterval
