# coding: utf-8

"""
    IPAssociations

    An IP association is a link between an IP reservation and the vcable of an instance. A vcable is an attachment point to a specific network interface of an instance. A vcable is created automatically when an instance is created and is deleted when the instance is deleted.<p>You can create, delete, and view IP associations using the HTTP requests listed below.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class HourlyInterval(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hourly_interval': 'int'
    }

    attribute_map = {
        'hourly_interval': 'hourlyInterval'
    }

    def __init__(self, hourly_interval=None):
        """
        HourlyInterval - a model defined in Swagger
        """

        self._hourly_interval = None

        if hourly_interval is not None:
          self.hourly_interval = hourly_interval

    @property
    def hourly_interval(self):
        """
        Gets the hourly_interval of this HourlyInterval.
        Hours to wait before starting the next backup

        :return: The hourly_interval of this HourlyInterval.
        :rtype: int
        """
        return self._hourly_interval

    @hourly_interval.setter
    def hourly_interval(self, hourly_interval):
        """
        Sets the hourly_interval of this HourlyInterval.
        Hours to wait before starting the next backup

        :param hourly_interval: The hourly_interval of this HourlyInterval.
        :type: int
        """

        self._hourly_interval = hourly_interval

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, HourlyInterval):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
