# coding: utf-8

"""
    IPAssociations

    An IP association is a link between an IP reservation and the vcable of an instance. A vcable is an attachment point to a specific network interface of an instance. A vcable is created automatically when an instance is created and is deleted when the instance is deleted.<p>You can create, delete, and view IP associations using the HTTP requests listed below.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class IPAssociationResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account': 'str',
        'ip': 'str',
        'name': 'str',
        'parentpool': 'str',
        'reservation': 'str',
        'uri': 'str',
        'vcable': 'str'
    }

    attribute_map = {
        'account': 'account',
        'ip': 'ip',
        'name': 'name',
        'parentpool': 'parentpool',
        'reservation': 'reservation',
        'uri': 'uri',
        'vcable': 'vcable'
    }

    def __init__(self, account=None, ip=None, name=None, parentpool=None, reservation=None, uri=None, vcable=None):
        """
        IPAssociationResponse - a model defined in Swagger
        """

        self._account = None
        self._ip = None
        self._name = None
        self._parentpool = None
        self._reservation = None
        self._uri = None
        self._vcable = None

        if account is not None:
          self.account = account
        if ip is not None:
          self.ip = ip
        if name is not None:
          self.name = name
        if parentpool is not None:
          self.parentpool = parentpool
        if reservation is not None:
          self.reservation = reservation
        if uri is not None:
          self.uri = uri
        if vcable is not None:
          self.vcable = vcable

    @property
    def account(self):
        """
        Gets the account of this IPAssociationResponse.
        Shows the default account for your identity domain.

        :return: The account of this IPAssociationResponse.
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """
        Sets the account of this IPAssociationResponse.
        Shows the default account for your identity domain.

        :param account: The account of this IPAssociationResponse.
        :type: str
        """

        self._account = account

    @property
    def ip(self):
        """
        Gets the ip of this IPAssociationResponse.
        The public IP address which is attached to an Oracle Compute Cloud Service instance that requires access to or from the Internet.

        :return: The ip of this IPAssociationResponse.
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """
        Sets the ip of this IPAssociationResponse.
        The public IP address which is attached to an Oracle Compute Cloud Service instance that requires access to or from the Internet.

        :param ip: The ip of this IPAssociationResponse.
        :type: str
        """

        self._ip = ip

    @property
    def name(self):
        """
        Gets the name of this IPAssociationResponse.
        The three-part name of the object (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>).

        :return: The name of this IPAssociationResponse.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this IPAssociationResponse.
        The three-part name of the object (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>).

        :param name: The name of this IPAssociationResponse.
        :type: str
        """

        self._name = name

    @property
    def parentpool(self):
        """
        Gets the parentpool of this IPAssociationResponse.
        <ul><li>To associate a temporary IP address from the pool, specify ippool:/oracle/public/ippool.</li><li>To associate a persistent IP address, specify ipreservation:ipreservation_name, where ipreservation_name is three-part name of an existing IP reservation in the <code>/Compute-identity_domain/user/object_name</code> format. For more information about how to create an IP reservation, see <a class=\"xref\" href=\"op-ip-reservation--post.html\">Create an IP Reservation</a>.</li><ul>

        :return: The parentpool of this IPAssociationResponse.
        :rtype: str
        """
        return self._parentpool

    @parentpool.setter
    def parentpool(self, parentpool):
        """
        Sets the parentpool of this IPAssociationResponse.
        <ul><li>To associate a temporary IP address from the pool, specify ippool:/oracle/public/ippool.</li><li>To associate a persistent IP address, specify ipreservation:ipreservation_name, where ipreservation_name is three-part name of an existing IP reservation in the <code>/Compute-identity_domain/user/object_name</code> format. For more information about how to create an IP reservation, see <a class=\"xref\" href=\"op-ip-reservation--post.html\">Create an IP Reservation</a>.</li><ul>

        :param parentpool: The parentpool of this IPAssociationResponse.
        :type: str
        """

        self._parentpool = parentpool

    @property
    def reservation(self):
        """
        Gets the reservation of this IPAssociationResponse.
        The three-part name of the IP reservation object in the format (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>). An IP reservation is a public IP address which is attached to an Oracle Compute Cloud Service instance that requires access to or from the Internet.

        :return: The reservation of this IPAssociationResponse.
        :rtype: str
        """
        return self._reservation

    @reservation.setter
    def reservation(self, reservation):
        """
        Sets the reservation of this IPAssociationResponse.
        The three-part name of the IP reservation object in the format (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>). An IP reservation is a public IP address which is attached to an Oracle Compute Cloud Service instance that requires access to or from the Internet.

        :param reservation: The reservation of this IPAssociationResponse.
        :type: str
        """

        self._reservation = reservation

    @property
    def uri(self):
        """
        Gets the uri of this IPAssociationResponse.
        Uniform Resource Identifier

        :return: The uri of this IPAssociationResponse.
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """
        Sets the uri of this IPAssociationResponse.
        Uniform Resource Identifier

        :param uri: The uri of this IPAssociationResponse.
        :type: str
        """

        self._uri = uri

    @property
    def vcable(self):
        """
        Gets the vcable of this IPAssociationResponse.
        The three-part name of a vcable ID of an instance that is associated with the IP reservation. The three-part name is in the format: <code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>.

        :return: The vcable of this IPAssociationResponse.
        :rtype: str
        """
        return self._vcable

    @vcable.setter
    def vcable(self, vcable):
        """
        Sets the vcable of this IPAssociationResponse.
        The three-part name of a vcable ID of an instance that is associated with the IP reservation. The three-part name is in the format: <code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>.

        :param vcable: The vcable of this IPAssociationResponse.
        :type: str
        """

        self._vcable = vcable

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, IPAssociationResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
